#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

defined('SOCKET_EAGAIN') || define('SOCKET_EAGAIN', 11);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = \yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/configs/common.php',
    require __DIR__ . '/configs/console.php'
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
